services:
  bird:
    image: mysql:latest
    container_name: bird
    environment:
      MYSQL_ROOT_PASSWORD: passw
      MYSQL_DATABASE: twitter
    ports:
      - "3308:3306"
    volumes:
      - bird-db-data:/var/lib/mysql
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: passw
      MYSQL_DATABASE: ums
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty123
    ports:
      - "3306:3306"
    volumes:
      - ums-db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  bird-db-data:
  ums-db-data:

