## Server
server:
  port: 9001

## MySQL
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3308/twitter?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: passw

ums:
  host: http://localhost
  port: 9000
  paths:
    user: /users/user
    introspect: /auth/introspect

app:
  jwt:
    issuer: ums-service

