apiVersion: v1
kind: Secret
metadata:
  name: mysql-ums-secret
  namespace: apps
  labels:
    app.kubernetes.io/part-of: bird
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: passw
  MYSQL_DATABASE: ums
  MYSQL_USER: user
  MYSQL_PASSWORD: qwerty123
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-twitter-secret
  namespace: apps
  labels:
    app.kubernetes.io/part-of: bird
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: passw
  MYSQL_DATABASE: twitter
---
apiVersion: v1
kind: Secret
metadata:
  name: ums-auth-secret
  namespace: apps
  labels:
    app.kubernetes.io/part-of: bird
type: Opaque
stringData:
  GITHUB_CLIENT_ID: Iv23lijPV04bvrLU7N5D
  GITHUB_CLIENT_SECRET: dc2e44deac5a54ee6ede71649698281c43626b4c
  GITHUB_REDIRECT_URI: http://app.local/api/ums/login/oauth2/code/github
